basePath: /
definitions:
  auth.Message:
    properties:
      phone:
        example: "+71234567890"
        type: string
      sms-code:
        example: "1234"
        type: string
    required:
    - phone
    - sms-code
    type: object
  controller.AuthLogoutResponse:
    properties:
      success:
        example: true
        type: boolean
    type: object
  controller.AuthResponse:
    properties:
      access-token:
        type: string
      is-new:
        type: boolean
      refresh-token:
        example: UUID
        type: string
      success:
        example: true
        type: boolean
      user-id:
        example: UUID
        type: string
    type: object
  controller.RefreshTokenResponse:
    properties:
      access:
        type: string
      id:
        example: UUID
        type: string
      refresh:
        example: UUID
        type: string
      success:
        example: true
        type: boolean
    type: object
  controller.SmsCodeResponse:
    properties:
      success:
        example: true
        type: boolean
    type: object
  controller.UserEditResponse:
    properties:
      success:
        example: true
        type: boolean
    type: object
  refreshToken.Message:
    properties:
      token:
        example: UUID
        type: string
    required:
    - token
    type: object
  sendSmsCode.Message:
    properties:
      phone:
        example: "+71234567890"
        type: string
    required:
    - phone
    type: object
  server.ResponseError:
    properties:
      message:
        example: Error message
        type: string
      success:
        example: false
        type: boolean
    type: object
  userEdit.Message:
    properties:
      name:
        example: New user name
        type: string
    required:
    - name
    type: object
  userLogout.Message:
    properties:
      token:
        example: uuid
        type: string
    required:
    - token
    type: object
host: localhost:8000
info:
  contact: {}
  description: Internal API
  title: Bigfood
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Get new refresh and access tokens
      parameters:
      - description: Body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.AuthResponse'
        "422":
          description: SMS code not confirmed
          schema:
            $ref: '#/definitions/server.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ResponseError'
      summary: User authorization
      tags:
      - auth
  /auth/logout:
    delete:
      consumes:
      - application/json
      description: Delete user refresh token
      parameters:
      - description: Body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/userLogout.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.AuthLogoutResponse'
        "400":
          description: Invalid refresh token
          schema:
            $ref: '#/definitions/server.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ResponseError'
      security:
      - ApiKeyAuth: []
      summary: User logout
      tags:
      - auth
  /auth/refresh-token:
    put:
      consumes:
      - application/json
      description: Refresh user refresh and access tokens
      parameters:
      - description: Body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/refreshToken.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.RefreshTokenResponse'
        "400":
          description: Invalid refresh token format
          schema:
            $ref: '#/definitions/server.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ResponseError'
      summary: Refresh jwt token
      tags:
      - auth
  /auth/sms-code:
    post:
      consumes:
      - application/json
      description: Send SMS code to user at authorization
      parameters:
      - description: Body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/sendSmsCode.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.SmsCodeResponse'
        "400":
          description: Phone number is invalid
          schema:
            $ref: '#/definitions/server.ResponseError'
        "429":
          description: Retry count of sms code requests exceeded
          schema:
            $ref: '#/definitions/server.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ResponseError'
      summary: Send SMS code
      tags:
      - auth
  /user:
    put:
      consumes:
      - application/json
      description: Edit user information
      parameters:
      - description: Body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/userEdit.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserEditResponse'
        "400":
          description: Invalid user data
          schema:
            $ref: '#/definitions/server.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ResponseError'
      security:
      - ApiKeyAuth: []
      summary: Edit user
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
